apiVersion: batch/v1
kind: Job
metadata:
  name: api-migrations
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: OnFailure
      initContainers:
      - name: wait-for-postgres
        image: busybox
        command:
          - sh
          - -c
          - |
            echo "Esperando pelo Postgres..."
            until nc -z postgres 5432; do
              echo "Postgres ainda não está pronto. Aguardando 2s..."
              sleep 2
            done
            echo "Postgres pronto!"
      containers:
      - name: migrate
        image: cstrader:latest
        command: ["poetry", "run", "alembic", "-c", "backend/alembic.ini", "upgrade", "head"]
        env:
        - name: DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: POSTGRES_USER
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: POSTGRES_PASSWORD
        - name: DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: POSTGRES_DB
